on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'psalm.xml'

  push:
    branches: ['master']
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'CHANGELOG.md'
      - '.gitignore'
      - '.gitattributes'
      - 'infection.json.dist'
      - 'psalm.xml'

name: build

permissions:
  contents: read
jobs:
  phpunit:
    uses: yiisoft/actions/.github/workflows/phpunit.yml@ab62d6b3b0e0cff6c9724ec5a395bedb41c639a2
    secrets:
      codecovToken: ${{ secrets.CODECOV_TOKEN }}
    with:
      os: >-
        ['ubuntu-latest', 'windows-latest']
      php: >-
        ['8.1', '8.2', '8.3', '8.4', '8.5']
