name: Rector + PHP CS Fixer

on:
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - '.github/workflows/rector-cs.yml'
      - 'composer.json'
      - 'rector.php'
      - '.php-cs-fixer.dist.php'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rector:
    uses: yiisoft/actions/.github/workflows/rector-cs.yml@ab62d6b3b0e0cff6c9724ec5a395bedb41c639a2
    with:
      php: '8.1'
